version: "3"
services:
  mariadb:
    env_file: .env
    build: ./requirements/mariadb
    volumes:
      - dbmaria:/var/www/html/
    networks:
      - web
    restart: unless-stopped

  wordpress:
    env_file: .env
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - wp_ngnx:/var/www/html/
    networks:
      - web
    restart: unless-stopped

  nginx:
    ports:
      - "443:443"
    build: ./requirements/nginx
    volumes:
      - wp_ngnx:/var/www/html/
    networks:
      - web
    restart: unless-stopped

networks:
  web:

volumes:
  dbmaria : 
    driver_opts:
      device: /home/mmarzouk/data/db
      type: none
      o: bind
  wp_ngnx : 
    driver_opts:
      device: /home/mmarzouk/data/wp
      type: none
      o: bind